sonar.projectKey=sonarqube_example
sonar.working.directory=C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\lucia\\RiderProjects\\sonarqube_example
sonar.pullrequest.cache.basepath=C:\\Users\\lucia\\RiderProjects\\sonarqube_example
sonar.sources=\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\docker-compose.yaml",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\sonar.sh"

CCDE44DE-BE02-4362-91AB-526617C1A2DA.sonar.projectKey=sonarqube_example:CCDE44DE-BE02-4362-91AB-526617C1A2DA
CCDE44DE-BE02-4362-91AB-526617C1A2DA.sonar.projectName=API.Tests
CCDE44DE-BE02-4362-91AB-526617C1A2DA.sonar.projectBaseDir=C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API.Tests
CCDE44DE-BE02-4362-91AB-526617C1A2DA.sonar.sourceEncoding=utf-8
CCDE44DE-BE02-4362-91AB-526617C1A2DA.sonar.sources=
CCDE44DE-BE02-4362-91AB-526617C1A2DA.sonar.tests=\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API.Tests\\UnitTest1.cs",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API.Tests\\obj\\API.Tests.csproj.nuget.dgspec.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API.Tests\\obj\\project.assets.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API.Tests\\obj\\project.packagespec.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API.Tests\\bin\\Debug\\net9.0\\API.Tests.deps.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API.Tests\\bin\\Debug\\net9.0\\API.Tests.runtimeconfig.json"

CCDE44DE-BE02-4362-91AB-526617C1A2DA.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\.sonarqube\\out\\0"
CCDE44DE-BE02-4362-91AB-526617C1A2DA.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\.sonarqube\\out\\0\\Issues.json"
CCDE44DE-BE02-4362-91AB-526617C1A2DA.sonar.cs.scanner.telemetry=\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\.sonarqube\\out\\0\\Telemetry.json"

CCDE44DE-BE02-4362-91AB-526617C1A2DA.sonar.working.directory=C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\.sonarqube\\out\\.sonar\\mod0
BB52ACDD-FDE9-4009-A0E7-60118F5134BD.sonar.projectKey=sonarqube_example:BB52ACDD-FDE9-4009-A0E7-60118F5134BD
BB52ACDD-FDE9-4009-A0E7-60118F5134BD.sonar.projectName=API
BB52ACDD-FDE9-4009-A0E7-60118F5134BD.sonar.projectBaseDir=C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API
BB52ACDD-FDE9-4009-A0E7-60118F5134BD.sonar.sourceEncoding=utf-8
BB52ACDD-FDE9-4009-A0E7-60118F5134BD.sonar.tests=
BB52ACDD-FDE9-4009-A0E7-60118F5134BD.sonar.sources=\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\appsettings.Development.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\appsettings.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\obj\\API.csproj.nuget.dgspec.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\obj\\project.assets.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\obj\\project.packagespec.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\Properties\\launchSettings.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\bin\\Debug\\net9.0\\API.deps.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\bin\\Debug\\net9.0\\API.runtimeconfig.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\bin\\Debug\\net9.0\\API.staticwebassets.endpoints.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\bin\\Debug\\net9.0\\appsettings.Development.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\bin\\Debug\\net9.0\\appsettings.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\obj\\Debug\\net9.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\obj\\Debug\\net9.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\obj\\Debug\\net9.0\\rpswa.dswa.cache.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\obj\\Debug\\net9.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\obj\\Debug\\net9.0\\staticwebassets.build.json",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\Program.cs",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\obj\\Debug\\net9.0\\API.GlobalUsings.g.cs",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\obj\\Debug\\net9.0\\.NETCoreApp,Version=v9.0.AssemblyAttributes.cs",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\obj\\Debug\\net9.0\\API.AssemblyInfo.cs",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\obj\\Debug\\net9.0\\API.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\API\\API.http"

BB52ACDD-FDE9-4009-A0E7-60118F5134BD.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\.sonarqube\\out\\1"
BB52ACDD-FDE9-4009-A0E7-60118F5134BD.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\.sonarqube\\out\\1\\Issues.json"
BB52ACDD-FDE9-4009-A0E7-60118F5134BD.sonar.cs.scanner.telemetry=\
"C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\.sonarqube\\out\\1\\Telemetry.json"

BB52ACDD-FDE9-4009-A0E7-60118F5134BD.sonar.working.directory=C:\\Users\\lucia\\RiderProjects\\sonarqube_example\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=CCDE44DE-BE02-4362-91AB-526617C1A2DA,BB52ACDD-FDE9-4009-A0E7-60118F5134BD

